name: Piso Exp SP5
on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar se já existe execução em andamento
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Conta quantas execuções deste workflow estão "em andamento"
          RUNNING_RUNS=$(gh run list --workflow "${{ github.workflow }}" --status in_progress --json databaseId --jq '. | length')
          
          # Se for maior que 1 (contando com esta própria execução), cancela a atual
          if [ "$RUNNING_RUNS" -gt 1 ]; then
            echo "Já existe uma execução deste script em andamento. Cancelando esta nova..."
            gh run cancel ${{ github.run_id }}
            exit 1 # Força a interrupção imediata do passo atual
          fi

      - name: Checkout do código
        uses: actions/checkout@v3
        
      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restaurar hxh.json
        shell: bash
        run: |
          echo "$GCP_JSON_BASE64" | base64 -d > hxh.json
        env:
          GCP_JSON_BASE64: ${{ secrets.GCP_JSON_BASE64 }}

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Executar o script
        run: xvfb-run python main.py